#NAME: Luca Matsumoto
#ID: 204726167
#EMAIL: lucamatsumoto@gmail.com

.SILENT:

default:
	gcc -g -Wall -Wextra lab1a.c -o lab1a

clean:
	rm -f *.o lab1a *.tar.gz

dist: default
	tar -czf lab1a-204726167.tar.gz lab1a.c Makefile README


